spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:file:.db/prodDB
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create